### ISSUE TITLE
Database: Creating the schema for database

### ISSUE THREAD

**Issue by ttiagojm** [ttiagojm/DailyMath#2]
#ToDo
Before starting to develop databases, we need to create the database format.
I think 2 tables are enough.

## Exercise table
* ID (INT, UNIQUE, NOT NULL, auto-incremental) => **Primary Key**
* type (VARCHAR, NOT NULL) => Represents the type of exercise (Linear Algebra, Calculus etc)
* source (VARCHAR, NOT NULL)  => Represents the author of the exercise
* exercise (BLOB or TEXT, NOT NULL) => Represents the exercise itself
* is_multiple_choice (BOOL, NOT NULL) => Represents if the exercise is multiple choice
* ID_solution (INT, UNIQUE, NOT NULL) => Foreign Key

## Multiple choice table
* ID (INT, UNIQUE, NOT NULL, auto-incremental) => **Primary Key**
* ID_exercise (INT, UNIQUE, NOT NULL, auto-incremental) => **Foreign Key**
* options (VARCHAR or TEXT, NOT NULL) => Options to be chosen by the user

## Solution table
* ID (INT, UNIQUE, NOT NULL, auto-incremental) => **Primary Key**
* solution (BLOB or TEXT, NOT NULL) => Solution for the exercise

## Explanations
Probably you're asking: "Why the multiple choice table doesn't have some flag saying what is the right answer?". Well, since all the exercises will have a detailed solution, the author will say, in the beggining, what solution is correct.

### ⚠️Warning ⚠️
Probably, because `options` will be a string with all options, some pattern will be developed to parse the options, but that's a back-end problem

**Comment by ttiagojm** [comment]
@ProgramingIsTheFuture 

1. If isn't multiple choice you do nothing just send the exercise, only if it is multiple choice they need to be fetched. Proof-based doesn't have options to be selected since user will write in a textbox
2. User don't  manage how many would appear, since who create options are the exercises' owners. All multiple choice exercises will have only 4 options (one right, the other 3 are wrong). User will select one of 4 as their final answer

**Comment by ProgramingIsTheFuture** [comment]
@ttiagojm

For the second question, that's what I'm referring to. The exercise owner might want to have just two options instead of 4 options. or might want something like this:
Option A - 10
Option B - 15
Option C - 20
Option D - 25
Option E - None

This way, we will limit the system to have always 4 choices. (Both of this cases have a single right answer that need to be specified in the database as well)

**Comment by ttiagojm** [comment]
@ProgramingIsTheFuture I already said will always have only 4 options less or more than that shouldn't be possible. Since just one will be right, the other ones are irrelevant so we can have a static number of inventend wrong answers.

**Comment by ttiagojm** [comment]
I don't but, this data is somewhat unstructed so a no relations database should be better ... What do you think ? @ProgramingIsTheFuture @Finalshare90

**Comment by ttiagojm** [comment]
@ProgramingIsTheFuture I'll do what you suggest, check the new schema please

**Comment by Finalshare90** [comment]
May i ask something?

Is the database format already set? i need to begin writing the requests for each case in back-end, but i'm not sure if i can use the format that @ttiagojm write above.

**Comment by Finalshare90** [comment]
And i am not sure if my idea is actually redundant, but would be very handy if each exercise had a key specifying *what kind* of exercise nature are they.

**Comment by ttiagojm** [comment]
@Finalshare90 wait for @ProgramingIsTheFuture to answer if the schema follows his idea.

When an exercise from Exercise table has is_multiple_choice then you need to go to Multiple choice table to get the options.

And yes, we can add an column "Type" to specifcy the type of exercise (lin alg, calculus, trig etc etc)

**Comment by ProgramingIsTheFuture** [comment]
The schema looks good to me and yes, it follows my idea.
And we might want to let the solution be something like latex or mathjax to render the formulas in the HTML.

**Comment by ttiagojm** [comment]
@ProgramingIsTheFuture Yes exercises and solutions will be in LaTeX to rendered in frontend

**Comment by ttiagojm** [comment]
![asd2 drawio](https://github.com/ttiagojm/DailyMath/assets/21047725/0f3fe39f-bb9c-4931-bcb1-433ccb7c25ab)

@Finalshare90 Here we have the database diagram

**Comment by ttiagojm** [comment]
Database was modeled and created
