### ISSUE TITLE
Backend: Request for exercise

### ISSUE THREAD

**Issue by ttiagojm** [ttiagojm/DailyMath#3]
# ToDo
* Backend should has some URI to send the daily exercise
* You should get the exercise from the right table
* If the exercise is multiple choice, the possible options should be sent together with the exercise

# Problems
* We need to think about a way to normalize how we will sent proof-based and multiple choice exercises, since the first one doesn't have options and the second has

**Comment by Finalshare90** [comment]
![getExercise](https://github.com/ttiagojm/DailyMath/assets/77998939/9b99ba74-7754-443e-a124-45c73c57684e)

I built a little diagram to illustrate my idea of how can we make it. Any opinions? i'm going to start building a prototype in a separated branch ASAP.

**Comment by ttiagojm** [comment]
Nice diagram! In terms of database I think the Exercise table on left it's the Multiple Choice Table and not Exercise table.
And Multiple Choice Table doesn't has the updates whose I made some hours ago (instead of opt1, opt2 ... we will have only a options field). Nice work dude ^^

**Comment by Finalshare90** [comment]
New related pull request #14

**Comment by ttiagojm** [comment]
The goals were accomplished in #14
